//! Names that are not applications, shared by every discovery path.
//!
//! Lived in `lnk.rs` through v0.2, which was the bug: `AppsFolder` mirrors Win32
//! apps and re-admitted everything the `.lnk` walk had just dropped. "Uninstall
//! Node.js" was filtered, then returned as `Microsoft.AutoGenerated.{A9EBB164-…}`
//! and ranked above the real Node.js for `node` (tbd v0.2 §9).
//!
//! Every path that produces a display name filters through here.

/// Shortcuts and shell entries that are not applications.
///
/// Installers drop these beside the thing you want, competing for the same
/// letters: `chr` must not offer "Uninstall Chrome" above Chrome. Deliberately
/// short — over-filtering hides real apps, which is far worse than noise.
pub fn is_noise(name: &str) -> bool {
    let lower = name.to_lowercase();
    const PREFIXES: &[&str] = &["uninstall ", "remove ", "modify "];
    const EXACT: &[&str] = &[
        "uninstall",
        "readme",
        "read me",
        "license",
        "licence",
        "changelog",
        "release notes",
        "documentation",
        "help",
        "website",
        "home page",
        "homepage",
    ];
    PREFIXES.iter().any(|p| lower.starts_with(p)) || EXACT.iter().any(|e| lower == *e)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn v0_2_installer_debris_is_filtered_out() {
        assert!(is_noise("Uninstall Google Chrome"));
        assert!(is_noise("uninstall"));
        assert!(is_noise("ReadMe"));
        assert!(is_noise("Release Notes"));
    }

    /// The filter must stay timid. An aggressive list starts hiding real
    /// applications, which is a much worse failure than a little noise in the list.
    #[test]
    fn v0_2_the_noise_filter_does_not_eat_real_applications() {
        assert!(!is_noise("Helper"));
        assert!(!is_noise("Adobe Photoshop"));
        assert!(!is_noise("Documentation Generator"));
        assert!(!is_noise("Website Builder"));
        assert!(!is_noise("HelpNDoc"));
    }
}
